//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.20 at 01:29:47 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pl/org/grzybek/tieto/endpoint/weather/soap/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.org.grzybek.tieto.endpoint.weather.soap.model;
